---
# cPanel automatic deployment configuration
# NOTE: Replace 'YOUR_CPANEL_USERNAME' with your actual cPanel username in the line below.
# (You can find this username in the upper-right corner of your cPanel homepage).
deployment:
  tasks:
    - export DEPLOYPATH=/home/yogaadve/kayastharoshan.com.np/
    - cp -R ./index.html ./style.css ./script.js ./assets $DEPLOYPATH
